/**
 * The canonical origin, in one place.
 *
 * Every absolute URL the site emits  -  sitemap entries, `robots.txt`, canonical tags, OG images  -
 * has to agree, and they are generated by four different files. A literal repeated per file is how
 * two of them end up pointing somewhere else for a release.
 *
 * The default is the canonical origin, not whichever host is serving. The docs ship from this
 * domain alone. Overriding this only makes sense for a second live surface.
 */
export const SITE = process.env.NEXT_PUBLIC_SITE_URL || 'https://agentdecksdk.com'
