#!/usr/bin/env python3
"""Refresh the `<!-- roadmap-sync -->` live-status tables in docs/delivery/ from GitHub."""

from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
REPO = "agentdecksdk/agentdeck"
PROJECT_NUMBER = "5"
# Deliberately not the repo owner. The board is a *user* project
# (github.com/users/sagi5060/projects/5), and a user project does not move when its repository is
# transferred  -  the repo went to the `agentdecksdk` org and the board stayed. Changing this to
# match REPO makes every lookup 404.
PROJECT_OWNER = "sagi5060"
GENERATED_NOTE = (
    "<!-- Generated by scripts/sync_roadmap.py from live GitHub state. "
    "Regenerate with `make roadmap-sync`; do not hand-edit between the markers. -->"
)


def run_json(args: list[str]) -> Any:
    out = subprocess.run(args, capture_output=True, text=True, check=True).stdout
    return json.loads(out)


def open_issues(*extra_args: str) -> list[dict]:
    return run_json(
        [
            "gh",
            "issue",
            "list",
            "--repo",
            REPO,
            "--state",
            "open",
            "--json",
            "number,title,milestone",
            "--limit",
            "200",
            *extra_args,
        ]
    )


def project_status_by_issue() -> dict[int, str]:
    items = run_json(
        [
            "gh",
            "project",
            "item-list",
            PROJECT_NUMBER,
            "--owner",
            PROJECT_OWNER,
            "--limit",
            "500",
            "--format",
            "json",
        ]
    )["items"]
    return {
        item["content"]["number"]: item.get("status", " - ") for item in items if "number" in item.get("content", {})
    }


def render_table(issues: list[dict], statuses: dict[int, str]) -> str:
    if not issues:
        return "*No open issues.*"
    rows = ["| # | Title | Milestone | Status |", "|---|---|---|---|"]
    for issue in sorted(issues, key=lambda i: i["number"]):
        milestone = issue["milestone"]["title"] if issue.get("milestone") else " - "
        status = statuses.get(issue["number"], " - ")
        rows.append(f"| #{issue['number']} | {issue['title']} | {milestone} | {status} |")
    return "\n".join(rows)


def replace_block(text: str, name: str, body: str) -> str:
    start, end = f"<!-- roadmap-sync:{name}:start -->", f"<!-- roadmap-sync:{name}:end -->"
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    if not pattern.search(text):
        raise SystemExit(f"marker {name!r} not found")
    return pattern.sub(f"{start}\n{GENERATED_NOTE}\n\n{body}\n{end}", text)


def sync_roadmap(statuses: dict[int, str]) -> Path:
    path = REPO_ROOT / "docs/delivery/roadmap-v3.1.md"
    milestones = ("v3.1  -  hardening", "v3.2  -  batteries", "v3.3  -  rooms & reach")
    issues = [issue for milestone in milestones for issue in open_issues("--milestone", milestone)]
    path.write_text(
        replace_block(path.read_text(encoding="utf-8"), "milestones", render_table(issues, statuses)), encoding="utf-8"
    )
    return path


def sync_findings(statuses: dict[int, str]) -> Path:
    path = REPO_ROOT / "docs/delivery/findings-register.md"
    issues = open_issues("--label", "finding")
    path.write_text(
        replace_block(path.read_text(encoding="utf-8"), "open", render_table(issues, statuses)), encoding="utf-8"
    )
    return path


def main() -> None:
    statuses = project_status_by_issue()
    for path in (sync_roadmap(statuses), sync_findings(statuses)):
        print(f"regenerated: {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
