#!/usr/bin/env python3
"""Copy repository-scoped Claude agents and skills into Codex's native layout."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CLAUDE_ROOT = REPO_ROOT / ".claude"
CODEX_AGENTS_ROOT = REPO_ROOT / ".codex" / "agents"
CODEX_SKILLS_ROOT = REPO_ROOT / ".agents" / "skills"
GENERATED_HEADER = "# Generated by scripts/sync_claude_to_codex.py; do not edit."


def read_claude_markdown(path: Path) -> tuple[dict[str, str], str]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{path} must start with YAML frontmatter")

    try:
        frontmatter_end = lines.index("---", 1)
    except ValueError as error:
        raise ValueError(f"{path} has unterminated YAML frontmatter") from error

    metadata: dict[str, str] = {}
    for line in lines[1:frontmatter_end]:
        if not line.strip():
            continue
        key, separator, value = line.partition(":")
        if not separator:
            raise ValueError(f"{path} has unsupported frontmatter line: {line}")
        metadata[key.strip()] = value.strip().strip("\"'")

    body = "\n".join(lines[frontmatter_end + 1 :]).strip()
    return metadata, body


def codex_instructions(metadata: dict[str, str], body: str) -> str:
    compatibility: list[str] = []
    if metadata.get("isolation") == "worktree":
        compatibility.append(
            "Preserve worktree isolation: before changing branches or files, create and use a dedicated git "
            "worktree outside the primary checkout, and run all task commands there."
        )
    if "Claude" in body or "Anthropic" in body:
        compatibility.append(
            "Treat Claude-specific attribution instructions as inapplicable in Codex. Do not add model or vendor "
            "attribution unless the user or repository explicitly requires it."
        )
    if not compatibility:
        return body

    rules = "\n".join(f"- {rule}" for rule in compatibility)
    return f"{body}\n\nCodex compatibility:\n{rules}"


def render_codex_agent(source: Path) -> tuple[str, str]:
    metadata, body = read_claude_markdown(source)
    name = metadata.get("name")
    description = metadata.get("description")
    if not name or not description or not body:
        raise ValueError(f"{source} requires name, description, and instructions")

    instructions = codex_instructions(metadata, body)
    comments = [GENERATED_HEADER]
    if model := metadata.get("model"):
        comments.append(f"# Claude model {json.dumps(model)} omitted; this agent inherits the active Codex model.")
    content = "\n".join(
        [
            *comments,
            f"name = {json.dumps(name, ensure_ascii=False)}",
            f"description = {json.dumps(description, ensure_ascii=False)}",
            f"developer_instructions = {json.dumps(instructions, ensure_ascii=False)}",
            "",
        ]
    )
    return name, content


def copy_skills() -> list[Path]:
    source_root = CLAUDE_ROOT / "skills"
    copied: list[Path] = []
    for source in sorted(source_root.iterdir()):
        if not source.is_dir() or not (source / "SKILL.md").is_file():
            continue
        destination = CODEX_SKILLS_ROOT / source.name
        shutil.copytree(source, destination, dirs_exist_ok=True)
        copied.append(destination)
    return copied


def convert_agents() -> list[Path]:
    source_root = CLAUDE_ROOT / "agents"
    converted: list[Path] = []
    for source in sorted(source_root.glob("*.md")):
        name, content = render_codex_agent(source)
        destination = CODEX_AGENTS_ROOT / f"{name}.toml"
        destination.write_text(content, encoding="utf-8")
        converted.append(destination)
    return converted


def main() -> None:
    if not CLAUDE_ROOT.is_dir():
        raise SystemExit(f"Claude configuration not found: {CLAUDE_ROOT}")

    CODEX_AGENTS_ROOT.mkdir(parents=True, exist_ok=True)
    CODEX_SKILLS_ROOT.mkdir(parents=True, exist_ok=True)

    skills = copy_skills()
    agents = convert_agents()

    for path in skills:
        print(f"copied skill: {path.relative_to(REPO_ROOT)}")
    for path in agents:
        print(f"converted agent: {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
