/**
 * The canonical origin, in one place.
 *
 * Every absolute URL the site emits — sitemap entries, `robots.txt`, canonical tags, OG images —
 * has to agree, and they are generated by four different files. When the docs move to
 * `agentdecksdk.com` this is the line that changes; a literal repeated per file is how two of them
 * end up pointing somewhere else for a release.
 */
export const SITE = process.env.NEXT_PUBLIC_SITE_URL || 'https://sagi5060.github.io/agentdeck'
