/**
 * The canonical origin, in one place.
 *
 * Every absolute URL the site emits — sitemap entries, `robots.txt`, canonical tags, OG images —
 * has to agree, and they are generated by four different files. A literal repeated per file is how
 * two of them end up pointing somewhere else for a release.
 *
 * The default is the canonical origin, not whichever host is serving. The docs ship to two live
 * surfaces — this domain and the `agentdecksdk.github.io/agentdeck` Pages mirror — and the mirror
 * must name the domain as canonical or the two compete for the same queries. Overriding this only
 * makes sense for a third surface; the mirror should leave it alone.
 */
export const SITE = process.env.NEXT_PUBLIC_SITE_URL || 'https://agentdecksdk.com'
