"""The innermost ring: schema only. No engine, no surface, no I/O.

``agentdeck.core`` may import stdlib and pydantic and nothing else — an
import-linter contract enforces it.
"""

from agentdeck.core.content import (
    KNOWN_BLOCK_TYPES,
    ContentBlock,
    DataBlock,
    ImageBlock,
    Input,
    KnownBlock,
    ResourceBlock,
    TextBlock,
    UnknownBlock,
    coerce_input,
)
from agentdeck.core.context import RunContext
from agentdeck.core.events import (
    KNOWN_KINDS,
    RESULT_PREVIEW_MAX,
    TERMINAL_KINDS,
    ArtifactCreated,
    Budget,
    ControlObserved,
    ControlRequested,
    ControlVerb,
    Custom,
    Event,
    InputAppended,
    KnownPayload,
    MessageCompleted,
    NodeUpdated,
    ProgressReported,
    RunCancelled,
    RunCompleted,
    RunContextSnapshot,
    RunFailed,
    RunInterrupted,
    RunPaused,
    RunResumed,
    RunStarted,
    SafePoint,
    StatusReported,
    TextDelta,
    ThoughtDelta,
    ToolCallCompleted,
    ToolCallStarted,
    UnknownEvent,
    Usage,
    UsageReported,
    check_contiguous,
    check_terminal,
)
from agentdeck.core.invocable import InvocableKind, InvocableSpec
from agentdeck.core.reporting import Reporter
from agentdeck.core.status import RunStatus, can_resume, status_of

__all__ = [
    "KNOWN_BLOCK_TYPES",
    "KNOWN_KINDS",
    "RESULT_PREVIEW_MAX",
    "TERMINAL_KINDS",
    "ArtifactCreated",
    "Budget",
    "ContentBlock",
    "ControlObserved",
    "ControlRequested",
    "ControlVerb",
    "Custom",
    "DataBlock",
    "Event",
    "ImageBlock",
    "Input",
    "InputAppended",
    "InvocableKind",
    "InvocableSpec",
    "KnownBlock",
    "KnownPayload",
    "MessageCompleted",
    "NodeUpdated",
    "ProgressReported",
    "Reporter",
    "ResourceBlock",
    "RunCancelled",
    "RunCompleted",
    "RunContext",
    "RunContextSnapshot",
    "RunFailed",
    "RunInterrupted",
    "RunPaused",
    "RunResumed",
    "RunStarted",
    "RunStatus",
    "SafePoint",
    "StatusReported",
    "TextBlock",
    "TextDelta",
    "ThoughtDelta",
    "ToolCallCompleted",
    "ToolCallStarted",
    "UnknownBlock",
    "UnknownEvent",
    "Usage",
    "UsageReported",
    "can_resume",
    "check_contiguous",
    "check_terminal",
    "coerce_input",
    "status_of",
]
