"""The innermost ring: schema only. No engine, no surface, no I/O.

``agentdeck.core`` may import stdlib and pydantic and nothing else — an
import-linter contract enforces it.
"""

from agentdeck.core.content import (
    ContentBlock,
    DataBlock,
    ImageBlock,
    Input,
    ResourceBlock,
    TextBlock,
    coerce_input,
)
from agentdeck.core.context import RunContext
from agentdeck.core.events import (
    KNOWN_KINDS,
    RESULT_PREVIEW_MAX,
    TERMINAL_KINDS,
    ArtifactCreated,
    Budget,
    Custom,
    Event,
    InputAppended,
    KnownPayload,
    MessageCompleted,
    NodeUpdated,
    RunCancelled,
    RunCompleted,
    RunContextSnapshot,
    RunFailed,
    RunInterrupted,
    RunPaused,
    RunResumed,
    RunStarted,
    TextDelta,
    ThoughtDelta,
    ToolCallCompleted,
    ToolCallStarted,
    UnknownEvent,
    Usage,
    UsageReported,
    check_contiguous,
    check_terminal,
    parse_event,
)
from agentdeck.core.invocable import InvocableKind, InvocableSpec

__all__ = [
    "KNOWN_KINDS",
    "RESULT_PREVIEW_MAX",
    "TERMINAL_KINDS",
    "ArtifactCreated",
    "Budget",
    "ContentBlock",
    "Custom",
    "DataBlock",
    "Event",
    "ImageBlock",
    "Input",
    "InputAppended",
    "InvocableKind",
    "InvocableSpec",
    "KnownPayload",
    "MessageCompleted",
    "NodeUpdated",
    "ResourceBlock",
    "RunCancelled",
    "RunCompleted",
    "RunContext",
    "RunContextSnapshot",
    "RunFailed",
    "RunInterrupted",
    "RunPaused",
    "RunResumed",
    "RunStarted",
    "TextBlock",
    "TextDelta",
    "ThoughtDelta",
    "ToolCallCompleted",
    "ToolCallStarted",
    "UnknownEvent",
    "Usage",
    "UsageReported",
    "check_contiguous",
    "check_terminal",
    "coerce_input",
    "parse_event",
]
